package exporter

import (
	"fmt"
	"io"
	"sort"
	"setupper/internal/manifest"
)

// Exporter defines the interface for generating target representation from a desired manifest
type Exporter interface {
	Export(des *manifest.DesiredManifest, w io.Writer) error
}

var registry = map[string]Exporter{
	"shell":    NewShellScriptExporter(),
	"brewfile": NewBrewfileExporter(),
}

// Get retrieves an exporter by name
func Get(name string) (Exporter, error) {
	exp, ok := registry[name]
	if !ok {
		return nil, fmt.Errorf("unknown exporter format: %s (supported: shell, brewfile)", name)
	}
	return exp, nil
}

// ShellScriptExporter generates a portable shell script to bootstrap a system
type ShellScriptExporter struct{}

// NewShellScriptExporter returns a new ShellScriptExporter
func NewShellScriptExporter() *ShellScriptExporter {
	return &ShellScriptExporter{}
}

// Export writes the shell script representation of the desired manifest to the writer
func (s *ShellScriptExporter) Export(des *manifest.DesiredManifest, w io.Writer) error {
	var formulas []manifest.Resource
	var casks []manifest.Resource
	var masApps []manifest.Resource

	for _, res := range des.Resources {
		switch res.Type {
		case "brew":
			formulas = append(formulas, res)
		case "cask":
			casks = append(casks, res)
		case "mas":
			masApps = append(masApps, res)
		}
	}

	sort.Slice(formulas, func(i, j int) bool { return formulas[i].Name < formulas[j].Name })
	sort.Slice(casks, func(i, j int) bool { return casks[i].Name < casks[j].Name })
	sort.Slice(masApps, func(i, j int) bool { return masApps[i].Name < masApps[j].Name })

	fmt.Fprintln(w, "#!/bin/bash")
	fmt.Fprintln(w, "# Generated by Setupper. Do not edit manually.")
	fmt.Fprintln(w, "set -euo pipefail")
	fmt.Fprintln(w, "")

	// Bootstrap Homebrew
	fmt.Fprintln(w, "# Install Homebrew if not present")
	fmt.Fprintln(w, "if ! command -v brew &>/dev/null; then")
	fmt.Fprintln(w, "    echo \"Installing Homebrew...\"")
	fmt.Fprintln(w, "    /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"")
	fmt.Fprintln(w, "    if [[ -f /opt/homebrew/bin/brew ]]; then")
	fmt.Fprintln(w, "        eval \"$(/opt/homebrew/bin/brew shellenv)\"")
	fmt.Fprintln(w, "    elif [[ -f /usr/local/bin/brew ]]; then")
	fmt.Fprintln(w, "        eval \"$(/usr/local/bin/brew shellenv)\"")
	fmt.Fprintln(w, "    fi")
	fmt.Fprintln(w, "fi")
	fmt.Fprintln(w, "")

	// Formulas
	if len(formulas) > 0 {
		fmt.Fprintln(w, "# Install Homebrew formulas")
		fmt.Fprintln(w, "echo \"Installing Homebrew formulas...\"")
		for _, f := range formulas {
			fmt.Fprintf(w, "if ! brew list --formula %q &>/dev/null; then\n", f.Name)
			fmt.Fprintf(w, "    echo \"Installing %s...\"\n", f.Name)
			fmt.Fprintf(w, "    brew install %q\n", f.Name)
			fmt.Fprintln(w, "else")
			fmt.Fprintf(w, "    echo %q is already installed.\n", f.Name)
			fmt.Fprintln(w, "fi")
		}
		fmt.Fprintln(w, "")
	}

	// Casks
	if len(casks) > 0 {
		fmt.Fprintln(w, "# Install Homebrew casks")
		fmt.Fprintln(w, "echo \"Installing Homebrew casks...\"")
		for _, c := range casks {
			fmt.Fprintf(w, "if ! brew list --cask %q &>/dev/null; then\n", c.Name)
			fmt.Fprintf(w, "    echo \"Installing %s...\"\n", c.Name)
			fmt.Fprintf(w, "    brew install --cask %q\n", c.Name)
			fmt.Fprintln(w, "else")
			fmt.Fprintf(w, "    echo %q is already installed.\n", c.Name)
			fmt.Fprintln(w, "fi")
		}
		fmt.Fprintln(w, "")
	}

	// Mas Apps
	if len(masApps) > 0 {
		fmt.Fprintln(w, "# Install mas CLI if needed")
		fmt.Fprintln(w, "if ! command -v mas &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing mas CLI...\"")
		fmt.Fprintln(w, "    brew install mas")
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")

		fmt.Fprintln(w, "# Install Mac App Store apps")
		fmt.Fprintln(w, "echo \"Installing Mac App Store apps...\"")
		for _, m := range masApps {
			id := m.Options["id"]
			if id == "" {
				fmt.Fprintf(w, "# Warning: Skipping %s due to missing mas id\n", m.Name)
				continue
			}
			fmt.Fprintf(w, "if ! mas list | grep -q \"^%s \" &>/dev/null; then\n", id)
			fmt.Fprintf(w, "    echo \"Installing %s...\"\n", m.Name)
			fmt.Fprintf(w, "    mas install %s\n", id)
			fmt.Fprintln(w, "else")
			fmt.Fprintf(w, "    echo %q is already installed.\n", m.Name)
			fmt.Fprintln(w, "fi")
		}
		fmt.Fprintln(w, "")
	}

	return nil
}

// BrewfileExporter generates a standard Homebrew Brewfile representation
type BrewfileExporter struct{}

// NewBrewfileExporter returns a new BrewfileExporter
func NewBrewfileExporter() *BrewfileExporter {
	return &BrewfileExporter{}
}

// Export writes the Brewfile representation of the desired manifest to the writer
func (b *BrewfileExporter) Export(des *manifest.DesiredManifest, w io.Writer) error {
	var formulas []manifest.Resource
	var casks []manifest.Resource
	var masApps []manifest.Resource

	for _, res := range des.Resources {
		switch res.Type {
		case "brew":
			formulas = append(formulas, res)
		case "cask":
			casks = append(casks, res)
		case "mas":
			masApps = append(masApps, res)
		}
	}

	sort.Slice(formulas, func(i, j int) bool { return formulas[i].Name < formulas[j].Name })
	sort.Slice(casks, func(i, j int) bool { return casks[i].Name < casks[j].Name })
	sort.Slice(masApps, func(i, j int) bool { return masApps[i].Name < masApps[j].Name })

	fmt.Fprintln(w, "# Generated by Setupper. Do not edit manually.")
	fmt.Fprintln(w, "")

	if len(formulas) > 0 {
		fmt.Fprintln(w, "# Formulas")
		for _, f := range formulas {
			fmt.Fprintf(w, "brew %q\n", f.Name)
		}
		fmt.Fprintln(w, "")
	}

	if len(casks) > 0 {
		fmt.Fprintln(w, "# Casks")
		for _, c := range casks {
			fmt.Fprintf(w, "cask %q\n", c.Name)
		}
		fmt.Fprintln(w, "")
	}

	if len(masApps) > 0 {
		fmt.Fprintln(w, "# Mac App Store")
		for _, m := range masApps {
			id := m.Options["id"]
			if id == "" {
				fmt.Fprintf(w, "# mas %q (missing id)\n", m.Name)
			} else {
				fmt.Fprintf(w, "mas %q, id: %s\n", m.Name, id)
			}
		}
		fmt.Fprintln(w, "")
	}

	return nil
}
