package exporter

import (
	"fmt"
	"io"
	"sort"
	"setupper/internal/manifest"
)

// Exporter defines the interface for generating target representation from a desired manifest
type Exporter interface {
	Export(des *manifest.DesiredManifest, w io.Writer) error
}

var registry = map[string]Exporter{
	"shell":    NewShellScriptExporter(),
	"brewfile": NewBrewfileExporter(),
}

// Get retrieves an exporter by name
func Get(name string) (Exporter, error) {
	exp, ok := registry[name]
	if !ok {
		return nil, fmt.Errorf("unknown exporter format: %s (supported: shell, brewfile)", name)
	}
	return exp, nil
}

// ShellScriptExporter generates a portable shell script to bootstrap a system
type ShellScriptExporter struct{}

// NewShellScriptExporter returns a new ShellScriptExporter
func NewShellScriptExporter() *ShellScriptExporter {
	return &ShellScriptExporter{}
}

// Export writes the shell script representation of the desired manifest to the writer
func (s *ShellScriptExporter) Export(des *manifest.DesiredManifest, w io.Writer) error {
	var formulas []manifest.Resource
	var casks []manifest.Resource
	var masApps []manifest.Resource
	var vscodeExts []manifest.Resource
	var cursorExts []manifest.Resource
	var npmPkgs []manifest.Resource
	var pnpmPkgs []manifest.Resource
	var cargoPkgs []manifest.Resource
	var pipxPkgs []manifest.Resource
	var uvPkgs []manifest.Resource
	var goPkgs []manifest.Resource
	var fonts []manifest.Resource
	var gitConfigs []manifest.Resource

	for _, res := range des.Resources {
		switch res.Type {
		case "brew":
			formulas = append(formulas, res)
		case "cask":
			casks = append(casks, res)
		case "mas":
			masApps = append(masApps, res)
		case "vscode-extension":
			vscodeExts = append(vscodeExts, res)
		case "cursor-extension":
			cursorExts = append(cursorExts, res)
		case "npm":
			npmPkgs = append(npmPkgs, res)
		case "pnpm":
			pnpmPkgs = append(pnpmPkgs, res)
		case "cargo":
			cargoPkgs = append(cargoPkgs, res)
		case "pipx":
			pipxPkgs = append(pipxPkgs, res)
		case "uv":
			uvPkgs = append(uvPkgs, res)
		case "go":
			goPkgs = append(goPkgs, res)
		case "font":
			fonts = append(fonts, res)
		case "git-config":
			gitConfigs = append(gitConfigs, res)
		}
	}

	sort.Slice(formulas, func(i, j int) bool { return formulas[i].Name < formulas[j].Name })
	sort.Slice(casks, func(i, j int) bool { return casks[i].Name < casks[j].Name })
	sort.Slice(masApps, func(i, j int) bool { return masApps[i].Name < masApps[j].Name })
	sort.Slice(vscodeExts, func(i, j int) bool { return vscodeExts[i].Name < vscodeExts[j].Name })
	sort.Slice(cursorExts, func(i, j int) bool { return cursorExts[i].Name < cursorExts[j].Name })
	sort.Slice(npmPkgs, func(i, j int) bool { return npmPkgs[i].Name < npmPkgs[j].Name })
	sort.Slice(pnpmPkgs, func(i, j int) bool { return pnpmPkgs[i].Name < pnpmPkgs[j].Name })
	sort.Slice(cargoPkgs, func(i, j int) bool { return cargoPkgs[i].Name < cargoPkgs[j].Name })
	sort.Slice(pipxPkgs, func(i, j int) bool { return pipxPkgs[i].Name < pipxPkgs[j].Name })
	sort.Slice(uvPkgs, func(i, j int) bool { return uvPkgs[i].Name < uvPkgs[j].Name })
	sort.Slice(goPkgs, func(i, j int) bool { return goPkgs[i].Name < goPkgs[j].Name })
	sort.Slice(fonts, func(i, j int) bool { return fonts[i].Name < fonts[j].Name })
	sort.Slice(gitConfigs, func(i, j int) bool { return gitConfigs[i].Name < gitConfigs[j].Name })

	fmt.Fprintln(w, "#!/bin/bash")
	fmt.Fprintln(w, "# Generated by Setupper. Do not edit manually.")
	fmt.Fprintln(w, "set -euo pipefail")
	fmt.Fprintln(w, "")

	// Bootstrap Homebrew
	fmt.Fprintln(w, "# Install Homebrew if not present")
	fmt.Fprintln(w, "if ! command -v brew &>/dev/null; then")
	fmt.Fprintln(w, "    echo \"Installing Homebrew...\"")
	fmt.Fprintln(w, "    /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"")
	fmt.Fprintln(w, "    if [[ -f /opt/homebrew/bin/brew ]]; then")
	fmt.Fprintln(w, "        eval \"$(/opt/homebrew/bin/brew shellenv)\"")
	fmt.Fprintln(w, "    elif [[ -f /usr/local/bin/brew ]]; then")
	fmt.Fprintln(w, "        eval \"$(/usr/local/bin/brew shellenv)\"")
	fmt.Fprintln(w, "    fi")
	fmt.Fprintln(w, "fi")
	fmt.Fprintln(w, "")

	// Formulas
	if len(formulas) > 0 {
		fmt.Fprintln(w, "# Install Homebrew formulas")
		fmt.Fprintln(w, "echo \"Installing Homebrew formulas...\"")
		for _, f := range formulas {
			fmt.Fprintf(w, "if ! brew list --formula %q &>/dev/null; then\n", f.Name)
			fmt.Fprintf(w, "    echo \"Installing %s...\"\n", f.Name)
			fmt.Fprintf(w, "    brew install %q\n", f.Name)
			fmt.Fprintln(w, "else")
			fmt.Fprintf(w, "    echo %q is already installed.\n", f.Name)
			fmt.Fprintln(w, "fi")
		}
		fmt.Fprintln(w, "")
	}

	// Casks
	if len(casks) > 0 {
		fmt.Fprintln(w, "# Install Homebrew casks")
		fmt.Fprintln(w, "echo \"Installing Homebrew casks...\"")
		for _, c := range casks {
			fmt.Fprintf(w, "if ! brew list --cask %q &>/dev/null; then\n", c.Name)
			fmt.Fprintf(w, "    echo \"Installing %s...\"\n", c.Name)
			fmt.Fprintf(w, "    brew install --cask %q\n", c.Name)
			fmt.Fprintln(w, "else")
			fmt.Fprintf(w, "    echo %q is already installed.\n", c.Name)
			fmt.Fprintln(w, "fi")
		}
		fmt.Fprintln(w, "")
	}

	// Mas Apps
	if len(masApps) > 0 {
		fmt.Fprintln(w, "# Install mas CLI if needed")
		fmt.Fprintln(w, "if ! command -v mas &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing mas CLI...\"")
		fmt.Fprintln(w, "    brew install mas")
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")

		fmt.Fprintln(w, "# Install Mac App Store apps")
		fmt.Fprintln(w, "echo \"Installing Mac App Store apps...\"")
		for _, m := range masApps {
			id := m.Options["id"]
			if id == "" {
				fmt.Fprintf(w, "# Warning: Skipping %s due to missing mas id\n", m.Name)
				continue
			}
			fmt.Fprintf(w, "if ! mas list | grep -q \"^%s \" &>/dev/null; then\n", id)
			fmt.Fprintf(w, "    echo \"Installing %s...\"\n", m.Name)
			fmt.Fprintf(w, "    mas install %s\n", id)
			fmt.Fprintln(w, "else")
			fmt.Fprintf(w, "    echo %q is already installed.\n", m.Name)
			fmt.Fprintln(w, "fi")
		}
		fmt.Fprintln(w, "")
	}

	// VS Code Extensions
	if len(vscodeExts) > 0 {
		fmt.Fprintln(w, "# Install VS Code extensions")
		fmt.Fprintln(w, "if command -v code &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing VS Code extensions...\"")
		for _, e := range vscodeExts {
			fmt.Fprintf(w, "    code --install-extension %q --force\n", e.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Cursor Extensions
	if len(cursorExts) > 0 {
		fmt.Fprintln(w, "# Install Cursor extensions")
		fmt.Fprintln(w, "if command -v cursor &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing Cursor extensions...\"")
		for _, e := range cursorExts {
			fmt.Fprintf(w, "    cursor --install-extension %q --force\n", e.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Git Configurations
	if len(gitConfigs) > 0 {
		fmt.Fprintln(w, "# Configure Git")
		fmt.Fprintln(w, "echo \"Applying Git global configurations...\"")
		for _, g := range gitConfigs {
			val := g.Options["value"]
			fmt.Fprintf(w, "git config --global %q %q\n", g.Name, val)
		}
		fmt.Fprintln(w, "")
	}

	// Fonts
	if len(fonts) > 0 {
		fmt.Fprintln(w, "# Install Fonts")
		fmt.Fprintln(w, "echo \"Installing custom fonts...\"")
		fmt.Fprintln(w, "mkdir -p \"$HOME/Library/Fonts\"")
		for _, f := range fonts {
			url := f.Options["url"]
			path := f.Options["path"]
			if url != "" {
				fmt.Fprintf(w, "if [ ! -f \"$HOME/Library/Fonts/%s\" ]; then\n", f.Name)
				fmt.Fprintf(w, "    curl -fsSL %q -o \"$HOME/Library/Fonts/%s\"\n", url, f.Name)
				fmt.Fprintln(w, "fi")
			} else if path != "" {
				fmt.Fprintf(w, "if [ ! -f \"$HOME/Library/Fonts/%s\" ]; then\n", f.Name)
				fmt.Fprintf(w, "    cp %q \"$HOME/Library/Fonts/%s\"\n", path, f.Name)
				fmt.Fprintln(w, "fi")
			}
		}
		fmt.Fprintln(w, "")
	}

	// Node packages
	if len(npmPkgs) > 0 {
		fmt.Fprintln(w, "# Install global npm packages")
		fmt.Fprintln(w, "if command -v npm &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing global npm packages...\"")
		for _, p := range npmPkgs {
			fmt.Fprintf(w, "    npm install -g %q\n", p.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Pnpm packages
	if len(pnpmPkgs) > 0 {
		fmt.Fprintln(w, "# Install global pnpm packages")
		fmt.Fprintln(w, "if command -v pnpm &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing global pnpm packages...\"")
		for _, p := range pnpmPkgs {
			fmt.Fprintf(w, "    pnpm add -g %q\n", p.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Cargo packages
	if len(cargoPkgs) > 0 {
		fmt.Fprintln(w, "# Install cargo packages")
		fmt.Fprintln(w, "if command -v cargo &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing cargo packages...\"")
		for _, p := range cargoPkgs {
			fmt.Fprintf(w, "    cargo install %q\n", p.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Pipx packages
	if len(pipxPkgs) > 0 {
		fmt.Fprintln(w, "# Install pipx packages")
		fmt.Fprintln(w, "if command -v pipx &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing pipx packages...\"")
		for _, p := range pipxPkgs {
			fmt.Fprintf(w, "    pipx install %q\n", p.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Uv packages
	if len(uvPkgs) > 0 {
		fmt.Fprintln(w, "# Install uv packages")
		fmt.Fprintln(w, "if command -v uv &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing uv tools...\"")
		for _, p := range uvPkgs {
			fmt.Fprintf(w, "    uv tool install %q\n", p.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	// Go packages
	if len(goPkgs) > 0 {
		fmt.Fprintln(w, "# Install go packages")
		fmt.Fprintln(w, "if command -v go &>/dev/null; then")
		fmt.Fprintln(w, "    echo \"Installing go packages...\"")
		for _, p := range goPkgs {
			fmt.Fprintf(w, "    go install %q@latest\n", p.Name)
		}
		fmt.Fprintln(w, "fi")
		fmt.Fprintln(w, "")
	}

	return nil
}

// BrewfileExporter generates a standard Homebrew Brewfile representation
type BrewfileExporter struct{}

// NewBrewfileExporter returns a new BrewfileExporter
func NewBrewfileExporter() *BrewfileExporter {
	return &BrewfileExporter{}
}

// Export writes the Brewfile representation of the desired manifest to the writer
func (b *BrewfileExporter) Export(des *manifest.DesiredManifest, w io.Writer) error {
	var formulas []manifest.Resource
	var casks []manifest.Resource
	var masApps []manifest.Resource
	var vscodeExts []manifest.Resource

	for _, res := range des.Resources {
		switch res.Type {
		case "brew":
			formulas = append(formulas, res)
		case "cask":
			casks = append(casks, res)
		case "mas":
			masApps = append(masApps, res)
		case "vscode-extension":
			vscodeExts = append(vscodeExts, res)
		}
	}

	sort.Slice(formulas, func(i, j int) bool { return formulas[i].Name < formulas[j].Name })
	sort.Slice(casks, func(i, j int) bool { return casks[i].Name < casks[j].Name })
	sort.Slice(masApps, func(i, j int) bool { return masApps[i].Name < masApps[j].Name })
	sort.Slice(vscodeExts, func(i, j int) bool { return vscodeExts[i].Name < vscodeExts[j].Name })

	fmt.Fprintln(w, "# Generated by Setupper. Do not edit manually.")
	fmt.Fprintln(w, "")

	if len(formulas) > 0 {
		fmt.Fprintln(w, "# Formulas")
		for _, f := range formulas {
			fmt.Fprintf(w, "brew %q\n", f.Name)
		}
		fmt.Fprintln(w, "")
	}

	if len(casks) > 0 {
		fmt.Fprintln(w, "# Casks")
		for _, c := range casks {
			fmt.Fprintf(w, "cask %q\n", c.Name)
		}
		fmt.Fprintln(w, "")
	}

	if len(masApps) > 0 {
		fmt.Fprintln(w, "# Mac App Store")
		for _, m := range masApps {
			id := m.Options["id"]
			if id == "" {
				fmt.Fprintf(w, "# mas %q (missing id)\n", m.Name)
			} else {
				fmt.Fprintf(w, "mas %q, id: %s\n", m.Name, id)
			}
		}
		fmt.Fprintln(w, "")
	}

	if len(vscodeExts) > 0 {
		fmt.Fprintln(w, "# VS Code Extensions")
		for _, e := range vscodeExts {
			fmt.Fprintf(w, "vscode %q\n", e.Name)
		}
		fmt.Fprintln(w, "")
	}

	return nil
}
